### PR TITLE
feat: watsonx discovery module

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description

This PR addresses the internal [Issue](https://github.ibm.com/GoldenEye/issues/issues/11378) to create watson Discovery module.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [x] Major release (`X.x.x`)

##### Release notes content
* created terraform module to provision IBM watson Discovery instance.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [x] If relevant, a test for the change is included or updated with this PR.
- [x] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by imprateeksh** [comment]
As there is no code yet in main branch yet - so upgrade test will not pass. Skipping it for the initial PR.

**Review by ocofaigh — CHANGES_REQUESTED** [review]
@imprateeksh Can you make same changes you did in WatsonX Assistant PR? 
Also it looks like Discovery supports Key Protect encryption when you choose the premium plan. 
image

Can you add support for this to the module (it should take in a KMS key CRN, and support creating the s2s auth policy). NOTE: There is no need to take in the KMS instance guid as input - the guid can be parsed from the KMS key CRN.
I suggest to add an advanced example which supports creating premium instance, with key protect

**Comment by imprateeksh** [comment]
> @imprateeksh Can you make same changes you did in WatsonX Assistant PR? Also it looks like Discovery supports Key Protect encryption when you choose the premium plan. image
> 
> Can you add support for this to the module (it should take in a KMS key CRN, and support creating the s2s auth policy). NOTE: There is no need to take in the KMS instance guid as input - the guid can be parsed from the KMS key CRN. I suggest to add an advanced example which supports creating premium instance, with key protect, and make sure there is a test for it. The upgrade test should use this example.

Sure @ocofaigh - I am already syncing the same suggestions here too. 
Regarding the Key protect thing , we are not able to access the `Premium plan`. Even if I add the KP changes, we will not be able to verify the correctness as we are not able to run the Premium plan. I have provided this info [here](https://github.ibm.com/GoldenEye/issues/issues/11378#issuecomment-98644546)

**Comment by ocofaigh** [comment]
@imprateeksh We need to get premium plan access in our account - please find out how. In the meantime, we can proceed with no KMS support until we can test it

**Comment by maheshwarishikha** [comment]
@imprateeksh One small suggestion, it would be good if we can change outputs name as `watson_discovery_crn`, `watson_discovery_...` .

**Comment by maheshwarishikha** [comment]
> @imprateeksh One small suggestion, it would be good if we can change outputs name as `watson_discovery_crn`, `watson_discovery_...` .

Referred this - https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-assistant/pull/5#discussion_r1862572657 and now I think we may not need this change for base module. May be for DA. Anyways, ignore for now.

**Review by maheshwarishikha — APPROVED** [review]
LGTM

**Pull request merged**
